### ISSUE TITLE
SDK Não funciona em MVC 4 (.Net 4)

### ISSUE THREAD

**Issue by FabricioMF100** [LeximSoluciones/Lexim-MercadoPago-Sdk#1]
Tentei utilizar seu SDK em um projeto MVC 4 (.Net 4) (Infelizmente no brasil a maioria dos provedores de hospedagem funcionam em medium-trust, impossibilitando o uso do MVC 5), e obtive erros ao executar o projeto devido a falta de dlls do pacote "Microsoft.Net.Compilers" pois o mesmo requer .Net 4.5 ou superior.

>Error	1	The "Microsoft.CodeAnalysis.BuildTasks.Csc" task could not be loaded from the assembly C:\****\packages\Microsoft.Net.Compilers.2.8.2\build\..\tools\Microsoft.Build.Tasks.CodeAnalysis.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. O sistema não pode encontrar o arquivo especificado. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by fberasategui** [comment]
@FabricioMF100 A versão [1.0.3](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/1.0.3) já está publicada, o que resolve esse problema.

Acabei de fazer um teste com esta versão e permite-me compilar e executar corretamente uma aplicação MVC no .NET 4.0

Desculpe meu português, é uma tradução automática do Google

**Comment by FabricioMF100** [comment]
Bom dia!
Primeiramente muito obrigado pelo retorno e parabéns pela iniciativa.

Hoje vim correndo ao trabalho para testar a nova versão, e tive 2 problemas.

Testei tanto na minha implementação, quanto no exemplo também do IpnHandler dispónivel aqui.

Um erro é referente ao merchantorder, está tento erros tanto em FindById e também no Load. Segue abaixo:

MercadoPago.Resources.MerchantOrder.FindById(id)
E também
MercadoPago.Resources.MerchantOrder().Load(id)

> System.ArgumentException was unhandled by user code HResult=-2147024809 Message=Método do conjunto de propriedades não encontrado. Source=mscorlib StackTrace: em System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) em System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index) em MercadoPago.Resource`1.CopyProperties(T source, T destination) em MercadoPago.Resource`1.FillResourceWithResponseData(T resource, MPAPIResponse response) em MercadoPago.Resource`1.ProcessResponse(T resource, MPAPIResponse response, HttpMethod httpMethod) em MercadoPago.Resource`1.Get(String path, Boolean useCache, Int32 requestTimeout, Int32 retries) em MercadoPago.Resources.MerchantOrder.FindById(String id, Boolean useCache) em SoAchoAkiAPI.Controllers.ntfmercadopagoController.Post(String topic, String id) na c:\Projetos\SoAchoAki\ServidorAPI\SoAchoAkiAPI\Controllers\ntfmercadopagoController.cs:linha 161 em lambda_method(Closure , Object , Object[] ) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.<GetExecutor>b__c(Object instance, Object[] methodParameters) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.<>c__DisplayClass5.<ExecuteAsync>b__4() em System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken) InnerException: 


O segundo é ao gerar um webcheckout, via preferences, ao utilizar o Save() disparou o seguinte erro:

> InvalidCastException: Não é possível converter um objeto do tipo 'System.Int32' no tipo 'System.String'.] System.ComponentModel.DataAnnotations.StringLengthAttribute.IsValid(Object value) +46 MercadoPago.Validation.<>c.<GetValidationErrors>b__0_4(<>f__AnonymousType4`2 <>h__TransparentIdentifier2) +92 System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +147 MercadoPago.Validation.<GetValidationErrors>d__0.MoveNext() +1573 System.Linq.<SelectManyIterator>d__23`3.MoveNext() +235 MercadoPago.Validation.<GetValidationErrors>d__0.MoveNext() +2254 System.Linq.<SelectManyIterator>d__23`3.MoveNext() +235 MercadoPago.Validation.<GetValidationErrors>d__0.MoveNext() +3325 System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) +387 System.Linq.Enumerable.ToList(IEnumerable`1 source) +58 MercadoPago.Validation.ValidationResult..ctor(IEnumerable`1 errors) +60 MercadoPago.Validation.Validator.GetValidationResult(T instance) +132 MercadoPago.Validation.Validator.Validate(T instance) +118 MercadoPago.Resource`1.Send(T resource, HttpMethod httpMethod, String path, Boolean useCache, Int32 requestTimeout, Int32 retries) +171MercadoPago.Resource`1.Post(String path, Boolean useCache, Int32 requestTimeout, Int32 retries) +203 MercadoPago.Resources.Preference.Save() +48 SoAchoAkiAPI.Controllers.AdminController.Vender(String id, String nome, String sobrenome, String email) in c:\Projetos\SoAchoAki\ServidorAPI\SoAchoAkiAPI\Controllers\AdminController.cs:128 lambda_method(Closure , ControllerBase , Object[] ) +377 System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +19 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +209 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +27 System.Web.Mvc.Async.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41() +28 System.Web.Mvc.Async.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _) +15 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +49 System.Web.Mvc.Async.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33() +57 System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +226 System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult) +15 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +49 System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +24 System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +102 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +44 System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +15 System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +54 System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +44 System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +12 System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +25 System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +44 System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +11 System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9748493 System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +159

**Comment by fberasategui** [comment]
@FabricioMF100 A versão [1.0.4](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/1.0.4) corrige esses dois erros.

Eu vou fechar este tópico desde que o erro original foi resolvido.
Se você encontrar mais erros, você pode abrir um thread separado.

Obrigado pelo feedback
