### ISSUE TITLE
Me sale: Invalid Payment Id: 4379340393 

### ISSUE THREAD

**Issue by andreuspvr** [LeximSoluciones/Lexim-MercadoPago-Sdk#10]
Hola estoy haciendo pruebas con este SDK y me sale: Invalid Payment Id: 4379340393 en:
Ipn.HandleNotification(topic, id, onPaymentReceived: OnPaymentReceived, onMerchantOrderReceived: OnMerchantOrderReceived);

ya  probé en la REST Console de Mercadopago con mi access token y ahi si me da bien la informacion de dicho payment.

No estoy en modo sandbox.

Curiosamente el OnMerchantOrderReceived si lo hace bien.

**Comment by fberasategui** [comment]
@andreuspvr Efectivamente era un bug en nuestro `IpnHandler`. 

Se encuentra resuelto en la versión [2.0.2](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/).

Te pido que actualices a esa versión e intentes nuevamente.
