### ISSUE TITLE
Clase SDK, metodo get y post

### ISSUE THREAD

**Issue by agustinm20** [LeximSoluciones/Lexim-MercadoPago-Sdk#17]
Porque no estan? Tienen pensado agregarlo? Gracias.

**Comment by fberasategui** [comment]
@agustinm20 el propósito de este SDK (y cualquier SDK, en realidad) es abstraer y ocultar los detalles de implementación de la tecnología subyacente. Si yo te expongo un método GET o POST que utilice JSON básicamente estoy [leakeando](https://en.wikipedia.org/wiki/Leaky_abstraction) los detalles de implementación de la API de MercadoPago, que es justamente lo que trata de abstraer este SDK.

Si vas a usar requests HTTP y JSON, tranquilamente podrías no usar el SDK directamente y usar `HttpClient`.

La verdadera pregunta es qué estás tratando de hacer, que requiera el uso de estos métodos.

**Comment by agustinm20** [comment]
Hola, me referia a los metodos que si tiene la clase de MP y no este fork. Ya lo pude solucionar por otro lado, lo uso para obtener dato de la API como installments.

De todas maneras tengo problemas al hacer Save del Payment, con la libería de MP y con esta, la de MP porque uso .net standard 2.0 y con esta no se porqué, me da este error:
{MercadoPago.MPException: An error has occured in the cache structure (REMOVE): System.Runtime.Caching is not supported on this platform.
   at MercadoPago.MPCache.RemoveFromCache(String key)

**Comment by fberasategui** [comment]
@agustinm20 si hay algun endpoint de la API que no esté contemplado en el SDK y lo estás consumiendo directamente via HTTP, te invito a hacer un PR en este repo agregando los métodos y clases correspondientes, agregando lo que falta.

Nosotros hicimos este SDK basándonos en el oficial de .NET y de otros lenguajes, ya que es un desastre el nivel de inconsistencia que tiene MP entre los SDK oficiales. Algunos tienen algunos endpoints, otros tienen otros, otros ni funcionan, y asi sucesivamente.

Y la documentación no ayuda demasiado tampoco.

Respecto del error que estás teniendo, hay un [issue](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/issues/11) abierto, que no he tenido tiempo de atacar. 

Momentáneamente lo que voy a hacer es sacar todo ese asunto del caché, ya que en la práctica no se usa. Ni en este SDK ni en el oficial. 

Dame un rato y publico una nueva versión a Nuget.

**Comment by fberasategui** [comment]
@agustinm20 Publicada la versión [2.0.4](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/2.0.4), que resuelve el issue de `System.Runtime.Caching`.

**Comment by agustinm20** [comment]
Muchas gracias! 
Ya lo probé y no me da ese problema.
Ahora me pide que ponga en el Payment el "PaymentMethodId", con el SDK de ML este dato no es necesario ponerlo, te aviso para que estes al tanto.
Saludos!
