### ISSUE TITLE
Problemas con implementacion

### ISSUE THREAD

**Issue by Fernyt486** [LeximSoluciones/Lexim-MercadoPago-Sdk#19]
Buenas noches.
Agradezco mucho tu aporte, la verdad que el SDK oficial me dio dolores de cabeza.
Tengo un problema, la aplicacion funciona correctamente al ejecutardes desde visual studio, pero al publicar desde iis o un hosting (donweb) al ejecutar  Process.Start(preference.InitPoint); no pasa nada. no dirige a otra ventana, y en la consola del navegador no registra error.

Alguna idea? necesitas el codigo? en definitiva, el codigo rellena un formulario mediante conexion sql y luego hago un checkout basico .. no necesito mas . Funciona perfecto de manera local.

Estaria agradecido si podes guiarme.

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using MercadoPago;
using System.Diagnostics;
using MercadoPago.Common;
using MercadoPago.DataStructures.Preference;
using MercadoPago.Resources;

public partial class Default2 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        
    }
    protected void Buscar_Click(object sender, EventArgs e)
    {
      {
        {

            Saldo.Text = "0";
            Nombre.Text = "Cliente Inexistente";
            

            
           
        } 
            
        if ((NroAbo.Text != ""))

               {string connectionStringSaltaCableColor;
                  SqlConnection connectionSaltaCableColor;
                  connectionStringSaltaCableColor = (ConfigurationManager.ConnectionStrings["SaltaCableColor"].ConnectionString);
                  connectionSaltaCableColor = new SqlConnection(connectionStringSaltaCableColor);
               try
               {
                connectionSaltaCableColor.Open(); 

                {DataView dvSql1 = (DataView)SqlSaldo.Select(DataSourceSelectArguments.Empty);
                foreach (DataRowView drvSql1 in dvSql1)
                {Saldo.Text = drvSql1["saldo"].ToString();

                
               {DataView dvSql2 = (DataView)SqlAbonado.Select(DataSourceSelectArguments.Empty);
               foreach (DataRowView drvSql2 in dvSql2)
               {Nombre.Text = drvSql2["ApeNom"].ToString();                 
                }}
               {
                   DataView dvSql3 = (DataView)SqlDireccion.Select(DataSourceSelectArguments.Empty);
                   foreach (DataRowView drvSql3 in dvSql3)
                   {
                       Direccion.Text = drvSql3["Domicilio"].ToString();
                   }
               }
               {
                   DataView dvSql4 = (DataView)SqlEstado.Select(DataSourceSelectArguments.Empty);
                   foreach (DataRowView drvSql4 in dvSql4)
                   {
                      Estado.Text = drvSql4["desEstAbonado"].ToString();
                   }
               }
               }}}
                 catch (Exception ex)
                {connectionSaltaCableColor.Close();
                  }}
                  

         {
            if ((NroAbo.Text == ""))
            {
               NroAbo.Focus(); 
                
          } }

        }

        
        Panel1.Visible = true;
        Pagar.Visible = true;

    }
    
    protected void Pagar_Click(object sender, EventArgs e)
    {
        {
            //MercadoPago.SDK.ClientId = "2498631303236605";
           // MercadoPago.SDK.ClientSecret = "hq7W9qDz47AydzvzMcLOHfOlSDRXi1rX";
            var preference = new Preference
            {
                UserAccessToken = "APP_USR-2498631303236605-061310-2bf09d375ae24d5b2d3544e03a18c99e__LA_LB__-256199552",
                Items =
    {
        new Item
        {
            Id = NroAbo.Text,
            Title = "Abono Salta Cable Color",
            Quantity = 1,
            CurrencyId = CurrencyId.ARS,
            UnitPrice = Convert.ToDecimal(Saldo.Text)
        }
    },
            };

            // save to MercadoPago
            preference.Save();

            // the InitPoint property contains the URL of the web checkout screen for this preference
            Process.Start(preference.InitPoint);
            
        }
    }
}

**Comment by Fernyt486** [comment]
Lo subi a un hosting gratuito y tengo el mismo error que iis (lo corregi configurando la autenticacion) pero aqui en este hosting no deberia tener ese problema. te dejo el error. System.ComponentModel.Win32Exception: Access is denied




Server Error in '/' Application.
Access is denied
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

**Exception Details: System.ComponentModel.Win32Exception: Access is denied**

Source Error:


Line 114:
Line 115:            // the InitPoint property contains the URL of the web checkout screen for this preference
Line 116:            Process.Start(preference.InitPoint);
Line 117:            
Line 118:        }

Source File: d:\DZHosts\LocalUser\fernyt586\www.MPSCC.somee.com\Default.aspx.cs    Line: 116

Stack Trace:


[Win32Exception (0x80004005): Access is denied]
   System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo) +774
   System.Diagnostics.Process.Start() +126
   System.Diagnostics.Process.Start(ProcessStartInfo startInfo) +53
   System.Diagnostics.Process.Start(String fileName) +38
   Default2.Pagar_Click(Object sender, EventArgs e) in d:\DZHosts\LocalUser\fernyt586\www.MPSCC.somee.com\Default.aspx.cs:116
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9786906
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +211
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +1696

**Comment by fberasategui** [comment]
@Fernyt486 `Process.Start` no es la forma de redirigir al usuario a una nueva página, en ninguno de los frameworks web de .NET. Desconozco como hacer eso en Webforms, que se considera una tecnología obsoleta.

Te sugiero que busques en la documentación oficial de Microsoft, o en Stackoverflow.

Cierro el issue ya que no se trata de un problema con el SDK.
