### ISSUE TITLE
MerchantOrder deserialization error

### ISSUE THREAD

**Issue by fberasategui** [LeximSoluciones/Lexim-MercadoPago-Sdk#2]
As [reported](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/issues/1#issuecomment-419642664) by @@FabricioMF100, `MerchantOrder.Load()` and `MerchantOrder.FindById()` both fail with exception:

> System.ArgumentException was unhandled by user code HResult=-2147024809 Message=Método do conjunto de propriedades não encontrado. Source=mscorlib StackTrace: em System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture) em System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index) em MercadoPago.Resource1.CopyProperties(T source, T destination) em MercadoPago.Resource1.FillResourceWithResponseData(T resource, MPAPIResponse response) em MercadoPago.Resource1.ProcessResponse(T resource, MPAPIResponse response, HttpMethod httpMethod) em MercadoPago.Resource1.Get(String path, Boolean useCache, Int32 requestTimeout, Int32 retries) em MercadoPago.Resources.MerchantOrder.FindById(String id, Boolean useCache) em SoAchoAkiAPI.Controllers.ntfmercadopagoController.Post(String topic, String id) na c:\Projetos\SoAchoAki\ServidorAPI\SoAchoAkiAPI\Controllers\ntfmercadopagoController.cs:linha 161 em lambda_method(Closure , Object , Object[] ) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.b__c(Object instance, Object[] methodParameters) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) em System.Web.Http.Controllers.ReflectedHttpActionDescriptor.<>c__DisplayClass5.b__4() em System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken) InnerException:

**Comment by FabricioMF100** [comment]
I tested version 1.0.4 and solved it perfectly.
