### ISSUE TITLE
System.ComponentModel.Win32Exception: 'El sistema no puede encontrar el archivo especificado'

### ISSUE THREAD

**Issue by hugocarregno** [LeximSoluciones/Lexim-MercadoPago-Sdk#25]
Buenas, uso net core 2.2 , el problema me lo dio Process.start()

lo solucione de esta manera:

var psi = new ProcessStartInfo
{
      FileName = preference.InitPoint,
      UseShellExecute = true
};

Process.Start(psi);

**Comment by pablopioli** [comment]
Process.Start tiene un problema en .NET core porque tenes que considerar las particularidades de cada sistema operativo.

https://github.com/dotnet/corefx/issues/10361

Ese codigo nunca va a funcionar, tenes que cambiarlo como indica ahi
