### ISSUE TITLE
InvalidCastException trying to validate Preference

### ISSUE THREAD

**Issue by fberasategui** [LeximSoluciones/Lexim-MercadoPago-Sdk#3]
As [reported](https://github.com/LeximSoluciones/Lexim-MercadoPago-Sdk/issues/1#issuecomment-419642664) by @FabricioMF100, resource validation fails for instances of `Preference` with the following exception:

> InvalidCastException: Não é possível converter um objeto do tipo 'System.Int32' no tipo 'System.String'.] System.ComponentModel.DataAnnotations.StringLengthAttribute.IsValid(Object value) +46 MercadoPago.Validation.<>c.b__0_4(<>f__AnonymousType42 <>h__TransparentIdentifier2) +92 System.Linq.WhereSelectEnumerableIterator2.MoveNext() +147 MercadoPago.Validation.d__0.MoveNext() +1573 System.Linq.d__233.MoveNext() +235 MercadoPago.Validation.<GetValidationErrors>d__0.MoveNext() +2254 System.Linq.<SelectManyIterator>d__233.MoveNext() +235 MercadoPago.Validation.d__0.MoveNext() +3325 System.Collections.Generic.List1..ctor(IEnumerable1 collection) +387 System.Linq.Enumerable.ToList(IEnumerable1 source) +58 MercadoPago.Validation.ValidationResult..ctor(IEnumerable1 errors) +60 MercadoPago.Validation.Validator.GetValidationResult(T instance) +132 MercadoPago.Validation.Validator.Validate(T instance) +118 MercadoPago.Resource1.Send(T resource, HttpMethod httpMethod, String path, Boolean useCache, Int32 requestTimeout, Int32 retries) +171MercadoPago.Resource1.Post(String path, Boolean useCache, Int32 requestTimeout, Int32 retries) +203 MercadoPago.Resources.Preference.Save() +48 SoAchoAkiAPI.Controllers.AdminController.Vender(String id, String nome, String sobrenome, String email) in c:\Projetos\SoAchoAki\ServidorAPI\SoAchoAkiAPI\Controllers\AdminController.cs:128 lambda_method(Closure , ControllerBase , Object[] ) +377 System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +19 System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary2 parameters) +209 System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary2 parameters) +27 System.Web.Mvc.Async.<>c__DisplayClass42.b__41() +28 System.Web.Mvc.Async.<>c__DisplayClass81.<BeginSynchronous>b__7(IAsyncResult _) +15 System.Web.Mvc.Async.WrappedAsyncResult1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +49 System.Web.Mvc.Async.<>c__DisplayClass39.b__33() +57 System.Web.Mvc.Async.<>c__DisplayClass4f.b__49() +226 System.Web.Mvc.Async.<>c__DisplayClass37.b__36(IAsyncResult asyncResult) +15 System.Web.Mvc.Async.WrappedAsyncResult1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +49 System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +24 System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +102 System.Web.Mvc.Async.WrappedAsyncResult1.End() +58 System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +44 System.Web.Mvc.<>c__DisplayClass1d.b__18(IAsyncResult asyncResult) +15 System.Web.Mvc.Async.<>c__DisplayClass4.b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult1.End() +58 System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +54 System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult1.End() +58 System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +44 System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +12 System.Web.Mvc.<>c__DisplayClass8.b__3(IAsyncResult asyncResult) +25 System.Web.Mvc.Async.<>c__DisplayClass4.b__3(IAsyncResult ar) +16 System.Web.Mvc.Async.WrappedAsyncResult`1.End() +58 System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +44 System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +11 System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9748493 System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +48 System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by FabricioMF100** [comment]
I tested version 1.0.4 and solved it perfectly.
