### ISSUE TITLE
Error al crear preference version 1.0.6

### ISSUE THREAD

**Issue by mg9101** [LeximSoluciones/Lexim-MercadoPago-Sdk#4]
En la version 1.0.6, al hacer preference.Save() da el siguiente error:

Error converting value "" to type 'MercadoPago.Common.PaymentTypeId'. Path 'payment_methods.excluded_payment_types[0].id', line 1, position 776.

Mi código es:

                    Dim item As New MercadoPago.DataStructures.Preference.Item
                    item.Id = idusuario.ToString
                    item.Description = titulo
                    item.Title = "AmC - Contratacion"
                    item.Quantity = 1
                    item.CurrencyId = Common.CurrencyId.ARS
                    item.UnitPrice = CDec(lbltotal.Text)

                    Dim payer As New MercadoPago.DataStructures.Preference.Payer
                    payer.Name = CType(Session("usuario"), Usuarios).Nombre
                    payer.Surname = CType(Session("usuario"), Usuarios).Apellido
                    payer.Email = CType(Session("usuario"), Usuarios).Email

                    Dim back_urls As New MercadoPago.DataStructures.Preference.BackUrls
                    back_urls.Success = url
                    back_urls.Failure = url
                    back_urls.Pending = urlpendiente

                    preference.Items.Add(item)
                    preference.UserAccessToken = prov.AccesToken
                    preference.Payer = payer
                    preference.AutoReturn = MercadoPago.Common.AutoReturnType.approved
                    preference.BackUrls = back_urls
                    preference.ExternalReference = (idusuario.ToString + idmercadoPago.ToString)
                    preference.Marketplace = "amc-app"
                    preference.Marketplace_fee = marketFee
                    'preference.PaymentMethods = payment_method

                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
                    preference.Save()

Hice un downgrade a la versión 1.0.4 y funciona perfectamente.

**Comment by fberasategui** [comment]
Resuelto en la versión 1.0.7
