### ISSUE TITLE
Haciendo Refund

### ISSUE THREAD

**Issue by hperezbaranda** [LeximSoluciones/Lexim-MercadoPago-Sdk#7]
Hola, estoy necesitando hacer un **refund** intenté con el SDK oficial, pero tiene problemas, porque no soporta .Net Core, como ya me habían explicado, asi que usando la SDK de Lexim intenté hacerlo de la siguiente forma:
` Payment pay =Payment.FindById(payment_id) `
 ` var refund = pay.Refund();`
No me da ningún error en la busqueda de _payment_, pero resulta que no ejecuta el _refund_, no da error ni nada, simplemente me devuelve el mismo pagamento, y cuando verifico en las actividades del vendedor, aun esta el dinero en su cuenta.

**Comment by fberasategui** [comment]
@hperezbaranda podrías revisar el valor de la propiedad `pay.Status` luego de ejecutar el `pay.Refund()`?

De todas formas hay una deficiencia en como se están manejando los errores en este caso, que viene arrastrada del SDK oficial. Voy a levantar un issue aparte para corregir eso.

**Comment by hperezbaranda** [comment]
@fberasategui Hola, ya probe y aun me sale _aproved_ que es el ultimo estado del pagamento, ahí verifico la transacción y aun está sin en la cuenta del vendedor.

**Comment by fberasategui** [comment]
@hperezbaranda 

Intentá con este código:

```csharp
    var refund = new Refund
    {
        PaymentId = payment_id
    };
    refund.Save();
```

Y luego del `refund.Save()` fijate el valor de la propiedad `refund.Errors`. Me da la impresión de que está fallando, pero por una deficiencia en el manejo de errores no te está mostrando el error concreto.

**Comment by hperezbaranda** [comment]
Ese `Refund ` es de` MercadoPago.DataStructures.Payment.Refund` o de `MercadoPago.Resources.Refund`

**Comment by hperezbaranda** [comment]
Para ambos me dice que no puedo hacer 
`PaymentId = payment_id`
porque PaymentId es de solo lectura.

**Comment by fberasategui** [comment]
@hperezbaranda Se encuentra publicada la versión [1.0.10](https://www.nuget.org/packages/Lexim.MercadoPago.Sdk/1.0.10). 

Te recomiendo que intentes con esa versión, utilizando tu código original. 
Si hay alguna falla, en lugar de fallar silenciosamente, ahora vas a obtener una excepción con el detalle del error.

Estaré atento a tu feedback.

Saludos

**Comment by hperezbaranda** [comment]
@fberasategui Hola, ya probé como me sugirió y este es el error que lanza:

> {
    "ClassName": "MercadoPago.MPException",
    "Message": null,
    "Data": null,
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at MercadoPago.Resource\`1.ProcessResponse(T resource, MPAPIResponse response, HttpMethod httpMethod)\r\n   at MercadoPago.Resource\`1.Send(T resource, HttpMethod httpMethod, String path, Boolean useCache, Int32 requestTimeout, Int32 retries)\r\n   at MercadoPago.Resource\`1.Post(String path, Boolean useCache, Int32 requestTimeout, Int32 retries)\r\n   at MercadoPago.Resources.Refund.Save()\r\n   .....",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146233088,
    "Source": "Lexim.MercadoPago",
    "WatsonBuckets": null,
    "RequestId": null,
    "StatusCode": 401
}

También usé la otra forma sugerida, de crear un objeto refund... pero continua con error que hablé en el comentario anterior.

Saludos

**Comment by fberasategui** [comment]
@hperezbaranda te está dando error 401 (no autorizado). Revisá que estés configurando correctamente las credenciales antes de hacer cualquier llamada a la API.

**Comment by hperezbaranda** [comment]
Estoy usando el token de producción, las demas consultas si funcionan, ahora es solo esa la que lanza ese error

**Comment by fberasategui** [comment]
@hperezbaranda me llama la atencion que no tengas nada en la propiedad `Error` de la excepción. Podes verificar debuggeando o algo?

**Comment by hperezbaranda** [comment]
Bueno finalmente intente usando el mismo endpoint que esta en el código:

> /v1/payments/{payment_id}/refunds/

y ahí si me da el mensaje de error que buscamos, y es el siguiente:

```
"message": "Unauthorized use of live credentials",
"error": "unauthorized",
"status": 401,  
"cause": [  
    {    
      "code": 7,   
      "description": "Unauthorized use of live credentials",
      "data": null   
    }  
]
```

Ahí al parecer no esta autorizada esa credencial para hacer _refund_ aún cuando es la credencial de producción.

**Comment by hperezbaranda** [comment]
al parecer era algun error que estaban trabajando, porque ya funciona correctamente, muchas gracias!!
